export default {
  type: 'document',
  name: 'siteConfig',
  title: 'Site Configuration',
  // After creating the first document, you can uncomment the line below to prevent duplicates:
  // __experimental_actions: ['update', 'publish'],
  fieldsets: [
    { name: 'seo', title: 'SEO & Metadata', options: { collapsible: true, collapsed: false } },
    { name: 'branding', title: 'Branding & Logos', options: { collapsible: true, collapsed: false } },
    { name: 'colors', title: 'Theme Colors', options: { collapsible: true, collapsed: false } },
    { name: 'chatbot', title: 'AI Chatbot', options: { collapsible: true, collapsed: true } },
    { name: 'social', title: 'Social Links', options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    // ─── SEO & Metadata ───────────────────────────────
    {
      name: 'siteTitle',
      title: 'Site Title',
      type: 'string',
      fieldset: 'seo',
      description: 'The main title of the website (e.g. "Ingo - BSCS Information Board")',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'siteTagline',
      title: 'Tagline',
      type: 'string',
      fieldset: 'seo',
      description: 'A short tagline appended to page titles (e.g. "Your CS Information on the Go")',
    },
    {
      name: 'siteDescription',
      title: 'Meta Description',
      type: 'text',
      fieldset: 'seo',
      rows: 3,
      description: 'Default meta description for SEO (recommended 150-160 characters)',
      validation: (Rule) => Rule.max(300),
    },
    {
      name: 'siteKeywords',
      title: 'Meta Keywords',
      type: 'array',
      fieldset: 'seo',
      of: [{ type: 'string' }],
      description: 'SEO keywords for the site',
      options: { layout: 'tags' },
    },
    {
      name: 'siteUrl',
      title: 'Site URL',
      type: 'url',
      fieldset: 'seo',
      description: 'The canonical URL of the site (e.g. https://uccingo.tech)',
      validation: (Rule) =>
        Rule.uri({ scheme: ['http', 'https'] }),
    },
    {
      name: 'author',
      title: 'Site Author',
      type: 'string',
      fieldset: 'seo',
      description: 'Author meta tag value (e.g. "Ingo Team")',
    },
    {
      name: 'language',
      title: 'Language',
      type: 'string',
      fieldset: 'seo',
      description: 'Language code (e.g. "en")',
      initialValue: 'en',
    },

    // ─── Branding & Logos ─────────────────────────────
    {
      name: 'logo',
      title: 'Site Logo (SVG / PNG)',
      type: 'image',
      fieldset: 'branding',
      description: 'The primary logo used in the navbar and favicon',
      options: { hotspot: true },
    },
    {
      name: 'ogImage',
      title: 'Default OG Image',
      type: 'image',
      fieldset: 'branding',
      description: 'Default Open Graph image for social sharing (1200×630 recommended)',
      options: { hotspot: true },
    },
    {
      name: 'appleTouchIcon',
      title: 'Apple Touch Icon',
      type: 'image',
      fieldset: 'branding',
      description: 'Icon used on iOS home screens',
    },

    // ─── Theme Colors ─────────────────────────────────
    {
      name: 'colorBackground',
      title: 'Background Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Main body background color',
      initialValue: '#0a0c10',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorButton',
      title: 'Button Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Primary button / accent color',
      initialValue: '#a50000',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorButtonText',
      title: 'Button Text Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Text color for buttons',
      initialValue: '#ffffff',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorNav',
      title: 'Navbar Text Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Color for navbar text/icons',
      initialValue: '#ffffff',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorHeader',
      title: 'Header / Accent Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Used for headings, highlights, and accents',
      initialValue: '#fe4c4c',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorTheme',
      title: 'Theme / Brand Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Browser theme-color and tile color (used in meta tags)',
      initialValue: '#d44694',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },
    {
      name: 'colorScrollbar',
      title: 'Scrollbar Accent Color',
      type: 'string',
      fieldset: 'colors',
      description: 'Scrollbar thumb color',
      initialValue: '#fae63a',
      validation: (Rule) => Rule.regex(/^#([0-9A-Fa-f]{3,8})$/, { name: 'hex color' }),
    },

    // ─── AI Chatbot ───────────────────────────────────
    {
      name: 'chatbotEnabled',
      title: 'Enable Chatbot',
      type: 'boolean',
      fieldset: 'chatbot',
      description: 'Toggle the AI chatbot on/off across the site',
      initialValue: true,
    },
    {
      name: 'chatbotModel',
      title: 'AI Model',
      type: 'string',
      fieldset: 'chatbot',
      description: 'The Gemini model to use (e.g. "gemini-2.5-flash")',
      initialValue: 'gemini-2.5-flash',
    },
    {
      name: 'chatbotSystemPrompt',
      title: 'System Prompt',
      type: 'text',
      fieldset: 'chatbot',
      rows: 10,
      description: 'Custom system prompt for the AI chatbot. Leave empty to use the built-in default prompt.',
    },
    {
      name: 'chatbotName',
      title: 'Chatbot Display Name',
      type: 'string',
      fieldset: 'chatbot',
      description: 'Name shown in the chatbot UI',
      initialValue: 'Ingo Assistant',
    },
    {
      name: 'chatbotWelcomeMessage',
      title: 'Welcome Message',
      type: 'text',
      fieldset: 'chatbot',
      rows: 3,
      description: 'The initial greeting message the chatbot shows',
    },

    // ─── Social Links ─────────────────────────────────
    {
      name: 'socialFacebook',
      title: 'Facebook URL',
      type: 'url',
      fieldset: 'social',
      validation: (Rule) => Rule.uri({ allowRelative: false, scheme: ['http', 'https'] }),
    },
    {
      name: 'socialTwitter',
      title: 'Twitter / X Handle',
      type: 'string',
      fieldset: 'social',
      description: 'e.g. @ingo_bscs',
    },
    {
      name: 'socialInstagram',
      title: 'Instagram URL',
      type: 'url',
      fieldset: 'social',
      validation: (Rule) => Rule.uri({ allowRelative: false, scheme: ['http', 'https'] }),
    },
    {
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      fieldset: 'social',
      description: 'Public contact email address',
    },
    {
      name: 'copyrightText',
      title: 'Copyright Text',
      type: 'string',
      fieldset: 'social',
      description: 'Footer copyright line (e.g. "Under the management of UCC North Computer Science Council")',
    },
  ],
  preview: {
    prepare() {
      return { title: 'Site Configuration' };
    },
  },
};
